name: Metrics
on:
  schedule: # Runs daily
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: yeeteing
          template: classic
          base: header, repositories
          config_timezone: America/Toronto

          # 🔖 Topics plugin (optional, if you want it too)
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15

          # 🧩 LeetCode plugin
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_user: loyeeteing
