name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: yeeteing
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Toronto
          filename: metrics.svg
          output_action: commit
          committer_branch: master   # or `main` if that’s your default
          committer_message: "chore: update metrics"

          # LeetCode plugin
          plugin_leetcode: yes
          plugin_leetcode_user: lo?   # your LeetCode username
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_recent: 10
